apiVersion: v1 
kind: Service 
metadata: 
 name: homer 
 namespace: homeserver 
spec: 
 ports: 
   - name: web 
     port: 8080 
     targetPort: web 
 selector: 
   app: homer 
--- 
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: homer 
  namespace: homeserver 
  labels: 
    app: homer 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: homer 
  template: 
    metadata: 
      labels: 
        app: homer 
    spec: 
      containers: 
        - name: homer 
          ports: 
           - name: web 
             containerPort: 8080 
          image: b4bz/homer 
          volumeMounts: 
            - name: homer-config 
              mountPath: "/www/assets" 
      volumes: 
        - name: homer-config 
          hostPath: 
            path: "/server/homer" 
            type: Directory 
--- 
apiVersion: networking.k8s.io/v1 
kind: Ingress 
metadata: 
 name: homer 
 namespace: homeserver 
 annotations: 
   cert-manager.io/issuer: "le-http" 
spec: 
 rules: 
   - host: dashboard.server.home 
     http: 
       paths: 
         - path: / 
           pathType: Prefix 
           backend: 
             service: 
               name: homer 
               port: 
                 name: web
